name: flutter_web_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: 2.15.1
  firebase_auth: 4.9.0
  firebase_core_web: 2.7.0
  firebase_auth_web: 5.8.0
  web: 0.4.0

  # Local storage
  shared_preferences: any
  
  # Environment variables
  flutter_dotenv: any
  
  # HTTP client
  http: ^1.1.0
  fetch_client: ^1.0.2
  
  # State management
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
